"""Together AI's code-generated Tev1 training data as extra jev-bench *training* sources.

The Tev1 recipe (github.com/togethercomputer/tev1, MIT) trains on 37,840 examples, 23,340 of them
generated by code: rule policies whose answer includes "insufficient information", ordered-rule
routing, and fictional research-summary classification. This script runs those generators from a
checkout at a pinned commit and converts their output to jev-bench records, for the "Together-style
data" arm of a Tier 2 run. Tev1's public-data half is left out: four of its five datasets (MNLI,
BoolQ, Banking77, SST-5) are jev-bench sources Jevify already trains on, and the fifth (AG News)
has no clear licence.

    python scripts/tev1_synthetic.py --tev1 <checkout of togethercomputer/tev1> \\
        --bench <jev-bench root> --out <augmented root>

Writes ``<out>/data/<source>/{train,validation}.jsonl`` for four new sources and links every
jev-bench source directory into ``<out>/data`` unchanged, so ``python -m jevify.train tier2 --bench
<out>`` trains on jev-bench plus the new sources and tests on jev-bench exactly as before (the new
sources have no test split). The sibling variants of one generated case -- the same rule with one
fact flipped or missing -- stay together: whole groups are taken, and train and validation come from
the generators' own separately-seeded train and dev splits.
"""
from __future__ import annotations

import argparse
import json
import os
import subprocess
import sys
from collections import OrderedDict
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from jevify.bench.record import BenchRecord, write_jsonl  # noqa: E402

TEV1_COMMIT = "1dde7782382c9f49d627153759b8d1deab426ce0"
# per source: records per split, the same cap Tier 2 applies to every jev-bench source
PER_SPLIT = {"train": 400, "validation": 100}


def generators(tev1: Path):
    head = subprocess.run(["git", "-C", str(tev1), "rev-parse", "HEAD"], capture_output=True, text=True).stdout.strip()
    if head != TEV1_COMMIT:
        raise SystemExit(f"{tev1} is at {head or '?'}, expected {TEV1_COMMIT}")
    os.environ["OPEN_JEV_ROOT"] = str(tev1)
    sys.path.insert(0, str(tev1))
    import build_dataset as v1   # noqa: E402  (Together's modules, stdlib only)
    import build_v2 as v2        # noqa: E402
    import build_v21 as v21      # noqa: E402
    return v1, v2, v21


def whole_groups(rows: list[dict], n: int) -> list[dict]:
    """As many complete sibling groups as fit in n rows, in generation order."""
    groups: OrderedDict[str, list[dict]] = OrderedDict()
    for r in rows:
        groups.setdefault(r["group_id"], []).append(r)
    out: list[dict] = []
    for g in groups.values():
        if len(out) + len(g) > n:
            break
        out.extend(g)
    return out


def to_record(row: dict, source: str, split: str) -> BenchRecord:
    criteria = {o["key"]: o["description"] for o in row["options"]}   # Together's own (permuted) order
    assert row["answer_key"] in criteria, row["id"]
    prov = row.get("provenance", {})
    return BenchRecord(
        id=f"{source}/{split}/{row['id']}", source=source, primitive="choice", split=split,
        state=row["state"], question={"type": "choice", "instructions": row["question"], "criteria": criteria},
        label=row["answer_key"],
        meta={"generator": f"togethercomputer/tev1@{TEV1_COMMIT[:7]}", "licence": "MIT", "group_id": row["group_id"],
              "variant": prov.get("variant", prov.get("option_variant"))})


def build(tev1: Path) -> dict[str, dict[str, list[BenchRecord]]]:
    v1, v2, v21 = generators(tev1)
    taxonomy = json.loads((tev1 / "configs" / "research-taxonomy.json").read_text(encoding="utf-8"))
    # generate generously, then take whole groups; each generator seeds by (split, index), so
    # "train" and "dev" never share a case
    raw = {
        "tev1_policy": {"train": v1.policy_records("train", 1200), "validation": v1.policy_records("dev", 300)},
        "tev1_policy_missing": {"train": v2.synthetic("train", 1200), "validation": v2.synthetic("dev", 300)},
        "tev1_routing": {"train": v2.synthetic("train", 1200, routing=True), "validation": v2.synthetic("dev", 300, routing=True)},
        "tev1_research": {"train": v21.build_research("train", 20, taxonomy["options"], taxonomy["question"]),
                          "validation": v21.build_research("dev", 4, taxonomy["options"], taxonomy["question"])},
    }
    out: dict[str, dict[str, list[BenchRecord]]] = {}
    for source, splits in raw.items():
        out[source] = {}
        for split, rows in splits.items():
            # research groups ("research-v21:<split>:<topic>:<i>") are generated topic by topic, so a
            # cut in generation order would keep the first three topics of 24: order by (i, topic)
            if source == "tev1_research":
                groups: OrderedDict[str, list[dict]] = OrderedDict()
                for r in rows:
                    groups.setdefault(r["group_id"], []).append(r)
                keyed = sorted((int(gid.rsplit(":", 1)[1]), k, gid) for k, gid in enumerate(groups))
                rows = [r for _, _, gid in keyed for r in groups[gid]]
            out[source][split] = [to_record(r, source, split) for r in whole_groups(rows, PER_SPLIT[split])]
    return out


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--tev1", type=Path, required=True)
    ap.add_argument("--bench", type=Path, required=True)
    ap.add_argument("--out", type=Path, required=True)
    a = ap.parse_args()
    if a.out.exists():
        raise SystemExit(f"{a.out} exists; choose a new directory")
    data = build(a.tev1)
    (a.out / "data").mkdir(parents=True)
    for d in sorted((a.bench / "data").iterdir()):
        if d.is_dir():
            os.symlink(d.resolve(), a.out / "data" / d.name, target_is_directory=True)
    os.symlink((a.bench / "manifest.json").resolve(), a.out / "manifest.json")
    summary = {"tev1_commit": TEV1_COMMIT, "bench": str(a.bench.resolve()), "sources": {}}
    for source, splits in data.items():
        for split, recs in splits.items():
            write_jsonl(a.out / "data" / source / f"{split}.jsonl", recs)
        summary["sources"][source] = {
            split: {"records": len(recs), "groups": len({r.meta["group_id"] for r in recs}),
                    "labels": {k: sum(r.label == k for r in recs) for k in sorted({r.label for r in recs})}}
            for split, recs in splits.items()}
    # no group may appear in both splits, and no state may repeat across them
    for source, splits in data.items():
        tr = {r.meta["group_id"] for r in splits["train"]}
        va = {r.meta["group_id"] for r in splits["validation"]}
        assert not tr & va, f"{source}: {len(tr & va)} groups in both splits"
        ts = {json.dumps(r.state, sort_keys=True) for r in splits["train"]}
        assert not ts & {json.dumps(r.state, sort_keys=True) for r in splits["validation"]}, f"{source}: shared state"
    (a.out / "tev1_synthetic.json").write_text(json.dumps(summary, indent=1), encoding="utf-8")
    print(json.dumps(summary, indent=1))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
